/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moddydev.java.decompiler;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Moddy
 */
public class JavaDecompiler extends javax.swing.JFrame {

    MetodosArchivos ma = new MetodosArchivos();
    String userName = System.getProperty("user.name");
    
    /**
     * Creates new form JavaDecompiler
     */
    public JavaDecompiler() {
        initComponents();
        
        setIconImage(getIconImage());
        setTitle("Java Decompiler");
        
        String carpetName = "C:\\Users\\" + userName + "\\Documents\\outputsJD";
        ma.crearCarpeta(carpetName);
        
        LanguagesConfig lc = new LanguagesConfig();
        ArrayList<String> lenguages = lc.languges();
        String systemLenguage = System.getProperty("user.language");
        
        System.out.println(systemLenguage);
        
        if (lenguages.contains(systemLenguage)){
            // Menu
            newConvertion.setText(lc.sL(systemLenguage, newConvertion.getText()));
            clearLog.setText(lc.sL(systemLenguage, clearLog.getText()));
            aboutOption.setText(lc.sL(systemLenguage, aboutOption.getText()));
            exitOptionMenu.setText(lc.sL(systemLenguage, exitOptionMenu.getText()));
            
            // Labels
            jLabel2.setText(lc.sL(systemLenguage, jLabel2.getText()));
            jLabel3.setText(lc.sL(systemLenguage, jLabel3.getText()));
            jLabel4.setText(lc.sL(systemLenguage, jLabel4.getText()));
            jLabel5.setText(lc.sL(systemLenguage, jLabel5.getText()));
            
            // Buttons
            bGeneratorComand.setText(lc.sL(systemLenguage, bGeneratorComand.getText()));
            bGenerateFile.setText(lc.sL(systemLenguage, bGenerateFile.getText()));
            bExecute.setText(lc.sL(systemLenguage, bExecute.getText()));
            bCopy.setText(lc.sL(systemLenguage, bCopy.getText()));
        }
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icon.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGeneratorComand = new javax.swing.JButton();
        tfEntrada = new javax.swing.JTextField();
        tfDestino = new javax.swing.JTextField();
        bGenerateFile = new javax.swing.JButton();
        tfRoute = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        listlog = new java.awt.List();
        bCopy = new javax.swing.JButton();
        bExecute = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newConvertion = new javax.swing.JMenuItem();
        clearLog = new javax.swing.JMenuItem();
        aboutOption = new javax.swing.JMenuItem();
        exitOptionMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        bGeneratorComand.setText("Generate Command");
        bGeneratorComand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGeneratorComandMouseClicked(evt);
            }
        });

        tfEntrada.setToolTipText("");

        bGenerateFile.setText("Generate File");
        bGenerateFile.setMaximumSize(new java.awt.Dimension(139, 25));
        bGenerateFile.setMinimumSize(new java.awt.Dimension(139, 25));
        bGenerateFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGenerateFileMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Route");

        jLabel3.setText("Folder with files");

        jLabel4.setText("Destination folder");

        jLabel5.setText("Output");

        bCopy.setText("Copy");
        bCopy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCopyMouseClicked(evt);
            }
        });

        bExecute.setText("EXECUTE");
        bExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExecuteActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        newConvertion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        newConvertion.setText("New");
        newConvertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newConvertionActionPerformed(evt);
            }
        });
        jMenu1.add(newConvertion);

        clearLog.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        clearLog.setText("Clear Log");
        clearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogActionPerformed(evt);
            }
        });
        jMenu1.add(clearLog);

        aboutOption.setText("About");
        aboutOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutOptionActionPerformed(evt);
            }
        });
        jMenu1.add(aboutOption);

        exitOptionMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        exitOptionMenu.setText("Exit");
        exitOptionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitOptionMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitOptionMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listlog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfRoute)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCopy))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bGeneratorComand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bGenerateFile, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bExecute, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGeneratorComand)
                    .addComponent(bGenerateFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bExecute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCopy)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listlog, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String f1 = "";
    String first = "\"C:\\Program Files\\JavaDecompiler-by-Moddy\\data\\Dependencies\\java-decompiler.jar\"";
    String second = "org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler -dgs=true";
    String carpet = "";
    String entrada = "";
    String destino = "";
    String comando;
    
    private void bGeneratorComandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGeneratorComandMouseClicked
        entrada = tfEntrada.getText() + "/";
        destino = tfDestino.getText() + "/";
        
        if (!tfEntrada.getText().isEmpty() && !tfDestino.getText().isEmpty()){
            comando = "java -cp " + first + " " + second + " " + entrada + " " + destino;
            listlog.add("> gc: Generated Command");
        }else{
            listlog.add("> Error: gc: Fill in the following fields -> Folder with files and Destination folder");
        }
    }//GEN-LAST:event_bGeneratorComandMouseClicked

    private void bGenerateFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGenerateFileMouseClicked
        if (!tfEntrada.getText().isEmpty() && !tfDestino.getText().isEmpty() && !tfRoute.getText().isEmpty()){
            
            carpet = tfRoute.getText();
            entrada = tfEntrada.getText() + "/";
            destino = tfDestino.getText() + "/";
            
            String cm1 = "cd "+ carpet;
            String cm2 = "java -cp " + first + " " + second + " " + entrada + " " + destino;
            String uni = tfEntrada.getText()+"decompilador.bat";
            String df = "C:\\Users\\"+ userName + "\\Documents\\outputsJD\\"+ uni;
        
            ma.crearArchivo(df);
            
            ma.escribirArchivo(df, cm1, false, true);
            
            ma.escribirArchivo(df, cm2, false, true);
            
            listlog.add("> gf: Archivo generado");
            
            listlog.add("> gf: Copy and paste the following into the search bar of your file explorer");
            listlog.add("> ejecutar: C:\\Users\\"+userName+"\\Documents\\outputsJD");
            comando = "C:\\Users\\"+userName+"\\Documents\\outputsJD";
            listlog.add("> gf: Find the file "+tfEntrada.getText()+"decompilador.bat");
            listlog.add("> gf: Read the file corroborating that it does not have malware");
            listlog.add("> gf: Search your Documents folder");
        }else{
            listlog.add("> Error: gf: Fill in all fields");
        }
    }//GEN-LAST:event_bGenerateFileMouseClicked

    private void bCopyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCopyMouseClicked
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection strSel = new StringSelection(comando);
        
        cb.setContents(strSel, null);
    }//GEN-LAST:event_bCopyMouseClicked

    private void exitOptionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitOptionMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitOptionMenuActionPerformed

    private void newConvertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newConvertionActionPerformed
        comando = "";
        carpet = "";
        entrada = "";
        destino = "";
        listlog.removeAll();
        tfRoute.setText("");
        tfEntrada.setText("");
        tfDestino.setText("");
    }//GEN-LAST:event_newConvertionActionPerformed

    private void clearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogActionPerformed
        listlog.removeAll();
    }//GEN-LAST:event_clearLogActionPerformed

    private void aboutOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutOptionActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "https://www.javadecompiler.ga");
        } catch (IOException ex) {
            Logger.getLogger(JavaDecompiler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aboutOptionActionPerformed

    private void bExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExecuteActionPerformed
        String file = "C:\\Windows\\Temp\\JavaDecompilerJD\\comando.bat";
        
        carpet = tfRoute.getText();
        entrada = tfEntrada.getText() + "/";
        destino = tfDestino.getText() + "/";
        
        if (!tfRoute.getText().isEmpty() && !tfEntrada.getText().isEmpty() && !tfDestino.getText().isEmpty()){
            ma.crearCarpeta("C:\\Windows\\Temp\\JavaDecompilerJD");
            ma.crearArchivo(file);
            ma.escribirArchivo(file, "cd " + carpet, false, true);
            ma.escribirArchivo(file, "java -cp " + first + " " + second + " " + entrada + " " + destino, false, true);
            listlog.add("> excute: Running");
            try {
                Runtime app = Runtime.getRuntime();
                app.exec("cmd.exe /K C:/Windows/Temp/JavaDecompilerJD/comando.bat");
                listlog.add("> excute: Process completed");
            } catch (IOException ex) {
                Logger.getLogger(JavaDecompiler.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            listlog.add("> execute: Fill in all fields");
        }
    }//GEN-LAST:event_bExecuteActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaDecompiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaDecompiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaDecompiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaDecompiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaDecompiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutOption;
    private javax.swing.JButton bCopy;
    private javax.swing.JButton bExecute;
    private javax.swing.JButton bGenerateFile;
    private javax.swing.JButton bGeneratorComand;
    private javax.swing.JMenuItem clearLog;
    private javax.swing.JMenuItem exitOptionMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.List listlog;
    private javax.swing.JMenuItem newConvertion;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfEntrada;
    private javax.swing.JTextField tfRoute;
    // End of variables declaration//GEN-END:variables
}
